const redisClient = require('snake-redis').createClient()
let QueueManager = require('../index')
let queueManager = new QueueManager({redis: redisClient})

async function test() {
	// await queueManager.changeStatus('quiet')
	await queueManager.changeStatus('running')
	await queueManager.changeConcurrency(3)
// queueManager.add('HelloJob').set({wait: 200}).perform_now('world')
	queueManager.add('HelloJob').set({wait: 0}).perform_later('world')
	queueManager.add('HelloJob').set({wait: 5}).perform_later('world')
	queueManager.add('HelloJob').set({wait: 5}).perform_later('world')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after1')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after2')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after3')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after4')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after5')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after6')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after7')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after8')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-afte9')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after10')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after11')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after12')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after13')
	queueManager.add('HelloJob').set({wait: 10}).perform_later('world-after14')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after15')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after17')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after19')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after20')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after21')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after22')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after23')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after24')
	queueManager.add('HelloJob').set({wait: 20}).perform_later('world-after25')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after26')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after27')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after28')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after29')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after30')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after31')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after32')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after33')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after34')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after35')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after36')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after37')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after38')
	queueManager.add('HelloJob').set({wait: 30}).perform_later('world-after39')
	queueManager.add('HelloJob').set({wait: 40}).perform_later('world-after40')
	queueManager.add('HelloJob').set({wait: 40}).perform_later('world-after41')
	queueManager.add('HelloJob').set({wait: 40}).perform_later('world-after42')
	queueManager.add('HelloJob').set({wait: 40}).perform_later('world-after')
	queueManager.add('HelloJob').set({wait: 40}).perform_later('world-after')
	queueManager.add('HelloJob').set({wait: 40}).perform_later('world-after')
}
test()